config/routes.rb
DEWTweet::Application.routes.draw do
  resources :tweets
  
  match "user" => "tweets#message"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base


	def index
		Twitter.configure do |config|
		config.consumer_key = '16dYPItixjFviYjbJPKWbQ'
		config.consumer_secret = 'wnTWD3HGbzs3G2gnCKvCy85zGnSLmwuoRkH46680'
		config.consumer_token = '57489566-pTTKFBzi0nz2eKB7Cabv9BlFguWxTcHEvbsJVt9tF'
		config.consumer_token_secret = 'RYaGeaE1PoJ8agNI0ztP9VQC2h0Ad1S466d6vgj1Y'
		end
	end
	
	def message
	
		return "sin user" if self.user.blank?
		Twitter.user_timeline(self.user).first.text
		Twitter.user_timeline(self.user).last.text
	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
	@tweet = Tweet.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  #metodo de rueba
  def message
	@tweet = Tweet.new(params[:tweet])
	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end
  
  
  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DEWTweet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Status</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= form_for(@tweet, :url => "user") do |f| %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  
   <div class="actions">
    <%= f.submit "Buscar" %>
  </div>
  
 <% end %>
  

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.user %></td>
    <td><%= tweet.status %></td>
    <td><%= tweet.message %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/message.html.erb
<%=@tweet.message%>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @tweet.user %>
</p>

<p>
  <b>Status:</b>
  <%= @tweet.status %>
</p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>